from __future__ import annotations

from pathlib import Path

ROOT_DIR = Path(__file__).resolve().parent
TEMPLATES_DIR = ROOT_DIR / "templates"

ENUMS = {
    "status_active_inactive": {"active", "inactive"},
    "source_confidence": {"official", "estimated", "manual"},
    "degree_type": {"academic", "professional"},
    "score_line_type": {"national_a", "national_b", "school", "retest"},
    "subject_category": {"politics", "english", "math", "major", "custom"},
    "subject_role": {"politics", "english", "math", "major_1", "major_2"},
    "source_type": {"brochure", "catalog", "retest_rule", "official_notice", "other"},
    "source_link_status": {"active", "invalid", "pending"},
}

DATASET_SPECS = {
    "schools.csv": {
        "columns": [
            "name",
            "short_name",
            "code",
            "province",
            "city",
            "school_type",
            "school_level",
            "has_graduate_school",
            "official_website",
            "graduate_website",
            "description",
            "sort_order",
            "status",
        ],
        "required_fields": {"name", "short_name", "province", "city", "school_type", "school_level"},
        "enum_fields": {"status": ENUMS["status_active_inactive"]},
        "bool_fields": {"has_graduate_school"},
        "int_fields": {"sort_order"},
        "url_fields": {"official_website", "graduate_website"},
        "unique_key_fields": ("name", "city"),
        "min_values": {"sort_order": 0},
    },
    "departments.csv": {
        "columns": ["school_name", "school_code", "department_name", "department_code", "website", "status"],
        "required_fields": {"school_name", "department_name"},
        "enum_fields": {"status": ENUMS["status_active_inactive"]},
        "url_fields": {"website"},
        "unique_key_fields": ("school_name", "school_code", "department_name"),
    },
    "subjects.csv": {
        "columns": ["name", "code", "category"],
        "required_fields": {"name", "category"},
        "enum_fields": {"category": ENUMS["subject_category"]},
        "unique_key_fields": ("name", "code"),
    },
    "books.csv": {
        "columns": ["title", "author", "publisher", "isbn", "edition", "cover_url"],
        "required_fields": {"title", "author", "publisher"},
        "url_fields": {"cover_url"},
    },
    "programs.csv": {
        "columns": [
            "school_name",
            "department_name",
            "program_name",
            "program_code",
            "degree_type",
            "discipline_category",
            "research_direction",
            "exam_math_required",
            "duration_years",
            "tuition_per_year",
            "notes",
            "status",
        ],
        "required_fields": {
            "school_name",
            "department_name",
            "program_name",
            "program_code",
            "degree_type",
            "discipline_category",
            "tuition_per_year",
        },
        "enum_fields": {
            "degree_type": ENUMS["degree_type"],
            "status": ENUMS["status_active_inactive"],
        },
        "bool_fields": {"exam_math_required"},
        "decimal_fields": {"duration_years", "tuition_per_year"},
        "unique_key_fields": ("school_name", "department_name", "program_code", "research_direction"),
        "min_values": {"duration_years": 0.1, "tuition_per_year": 0},
    },
    "program_admissions.csv": {
        "columns": [
            "school_name",
            "department_name",
            "program_code",
            "program_name",
            "research_direction",
            "exam_year",
            "planned_enrollment",
            "recommended_exemption_count",
            "unified_exam_quota",
            "actual_enrollment",
            "is_cross_major_allowed",
            "memo",
            "source_confidence",
        ],
        "required_fields": {
            "school_name",
            "department_name",
            "program_code",
            "program_name",
            "exam_year",
            "planned_enrollment",
            "source_confidence",
        },
        "enum_fields": {"source_confidence": ENUMS["source_confidence"]},
        "bool_fields": {"is_cross_major_allowed"},
        "int_fields": {
            "exam_year",
            "planned_enrollment",
            "recommended_exemption_count",
            "unified_exam_quota",
            "actual_enrollment",
        },
        "unique_key_fields": ("school_name", "department_name", "program_code", "research_direction", "exam_year"),
        "min_values": {
            "exam_year": 2000,
            "planned_enrollment": 0,
            "recommended_exemption_count": 0,
            "unified_exam_quota": 0,
            "actual_enrollment": 0,
        },
    },
    "program_score_lines.csv": {
        "columns": [
            "school_name",
            "department_name",
            "program_code",
            "program_name",
            "research_direction",
            "exam_year",
            "score_line_type",
            "total_score",
            "politics_score",
            "english_score",
            "subject_one_score",
            "subject_two_score",
            "notes",
            "source_confidence",
        ],
        "required_fields": {
            "school_name",
            "department_name",
            "program_code",
            "program_name",
            "exam_year",
            "score_line_type",
            "total_score",
            "politics_score",
            "english_score",
            "subject_one_score",
            "subject_two_score",
            "source_confidence",
        },
        "enum_fields": {
            "score_line_type": ENUMS["score_line_type"],
            "source_confidence": ENUMS["source_confidence"],
        },
        "int_fields": {
            "exam_year",
            "total_score",
            "politics_score",
            "english_score",
            "subject_one_score",
            "subject_two_score",
        },
        "unique_key_fields": (
            "school_name",
            "department_name",
            "program_code",
            "research_direction",
            "exam_year",
            "score_line_type",
        ),
        "min_values": {
            "exam_year": 2000,
            "total_score": 0,
            "politics_score": 0,
            "english_score": 0,
            "subject_one_score": 0,
            "subject_two_score": 0,
        },
    },
    "program_application_stats.csv": {
        "columns": [
            "school_name",
            "department_name",
            "program_code",
            "program_name",
            "research_direction",
            "exam_year",
            "applicant_count",
            "actual_exam_count",
            "admitted_count",
            "application_ratio",
            "notes",
            "source_confidence",
        ],
        "required_fields": {
            "school_name",
            "department_name",
            "program_code",
            "program_name",
            "exam_year",
            "applicant_count",
            "admitted_count",
            "application_ratio",
            "source_confidence",
        },
        "enum_fields": {"source_confidence": ENUMS["source_confidence"]},
        "int_fields": {"exam_year", "applicant_count", "actual_exam_count", "admitted_count"},
        "decimal_fields": {"application_ratio"},
        "unique_key_fields": ("school_name", "department_name", "program_code", "research_direction", "exam_year"),
        "min_values": {
            "exam_year": 2000,
            "applicant_count": 0,
            "actual_exam_count": 0,
            "admitted_count": 0,
            "application_ratio": 0,
        },
    },
    "program_interview_stats.csv": {
        "columns": [
            "school_name",
            "department_name",
            "program_code",
            "program_name",
            "research_direction",
            "exam_year",
            "retest_candidate_count",
            "final_admitted_count",
            "interview_ratio",
            "retest_weight",
            "initial_exam_weight",
            "notes",
            "source_confidence",
        ],
        "required_fields": {
            "school_name",
            "department_name",
            "program_code",
            "program_name",
            "exam_year",
            "retest_candidate_count",
            "final_admitted_count",
            "interview_ratio",
            "retest_weight",
            "initial_exam_weight",
            "source_confidence",
        },
        "enum_fields": {"source_confidence": ENUMS["source_confidence"]},
        "int_fields": {"exam_year", "retest_candidate_count", "final_admitted_count"},
        "decimal_fields": {"interview_ratio", "retest_weight", "initial_exam_weight"},
        "unique_key_fields": ("school_name", "department_name", "program_code", "research_direction", "exam_year"),
        "min_values": {
            "exam_year": 2000,
            "retest_candidate_count": 0,
            "final_admitted_count": 0,
            "interview_ratio": 0,
            "retest_weight": 0,
            "initial_exam_weight": 0,
        },
        "max_values": {"retest_weight": 100, "initial_exam_weight": 100},
    },
    "program_exam_subjects.csv": {
        "columns": [
            "school_name",
            "department_name",
            "program_code",
            "program_name",
            "research_direction",
            "exam_year",
            "sequence_no",
            "subject_role",
            "subject_code_text",
            "subject_name_text",
            "subject_code",
            "notes",
        ],
        "required_fields": {
            "school_name",
            "department_name",
            "program_code",
            "program_name",
            "exam_year",
            "sequence_no",
            "subject_role",
            "subject_name_text",
        },
        "enum_fields": {"subject_role": ENUMS["subject_role"]},
        "int_fields": {"exam_year", "sequence_no"},
        "unique_key_fields": (
            "school_name",
            "department_name",
            "program_code",
            "research_direction",
            "exam_year",
            "sequence_no",
        ),
        "min_values": {"exam_year": 2000, "sequence_no": 1},
        "max_values": {"sequence_no": 4},
    },
    "program_reference_books.csv": {
        "columns": [
            "school_name",
            "department_name",
            "program_code",
            "program_name",
            "research_direction",
            "exam_year",
            "subject_role",
            "book_title",
            "book_author",
            "book_publisher",
            "book_isbn",
            "is_required",
            "notes",
        ],
        "required_fields": {
            "school_name",
            "department_name",
            "program_code",
            "program_name",
            "exam_year",
            "subject_role",
            "book_title",
            "book_author",
            "book_publisher",
        },
        "enum_fields": {"subject_role": ENUMS["subject_role"]},
        "bool_fields": {"is_required"},
        "int_fields": {"exam_year"},
        "unique_key_fields": (
            "school_name",
            "department_name",
            "program_code",
            "research_direction",
            "exam_year",
            "subject_role",
            "book_title",
            "book_author",
            "book_publisher",
            "book_isbn",
        ),
        "min_values": {"exam_year": 2000},
    },
    "program_source_links.csv": {
        "columns": [
            "school_name",
            "department_name",
            "program_code",
            "program_name",
            "research_direction",
            "exam_year",
            "source_type",
            "title",
            "url",
            "publisher_name",
            "published_at",
            "last_verified_at",
            "status",
            "source_confidence",
            "notes",
        ],
        "required_fields": {
            "school_name",
            "department_name",
            "program_code",
            "program_name",
            "exam_year",
            "source_type",
            "title",
            "url",
            "publisher_name",
            "last_verified_at",
            "status",
            "source_confidence",
        },
        "enum_fields": {
            "source_type": ENUMS["source_type"],
            "status": ENUMS["source_link_status"],
            "source_confidence": ENUMS["source_confidence"],
        },
        "int_fields": {"exam_year"},
        "date_fields": {"published_at"},
        "datetime_fields": {"last_verified_at"},
        "url_fields": {"url"},
        "unique_key_fields": ("school_name", "department_name", "program_code", "research_direction", "exam_year", "url"),
        "min_values": {"exam_year": 2000},
    },
}

DEFAULT_TEMPLATE_FILES = list(DATASET_SPECS.keys())


def known_filenames() -> set[str]:
    return set(DATASET_SPECS.keys())
